-- This file should undo anything in `up.sql`
DROP MATERIALIZED VIEW IF EXISTS twap_1_day_agg;
DROP MATERIALIZED VIEW IF EXISTS price_1_d_agg;
DROP MATERIALIZED VIEW IF EXISTS one_day_candle;
DROP MATERIALIZED VIEW IF EXISTS twap_1_week_agg;
DROP MATERIALIZED VIEW IF EXISTS price_1_w_agg;
DROP MATERIALIZED VIEW IF EXISTS one_week_candle;