[package]
name = "pragma-consumer"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://pragma.build/"
repository = "https://github.com/astraly-labs/pragma-node/"
description = "SDK to consume Pragma data feeds"
readme = "README.md"
keywords = ["pragma", "sdk", "consumer", "data", "feeds"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-diesel = { workspace = true, features = ["postgres"] }
dotenvy = { workspace = true }
envy = { workspace = true }
lazy_static = { workspace = true }
rdkafka = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

pragma-common = { path = "../pragma-common" }
pragma-entities = { path = "../pragma-entities" }
