[package]
name = "pragma-consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
color-eyre = { workspace = true }
deadpool-diesel = { workspace = true, features = ["postgres"] }
dotenvy = { workspace = true }
envy = { workspace = true }
lazy_static = { workspace = true }
rdkafka = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starknet-crypto = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

pragma-common = { path = "../pragma-common" }
pragma-entities = { path = "../pragma-entities" }

[dev-dependencies]
rstest = { workspace = true }
