[package]
name = "pragma-node"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = { version = "0.6", features = ["macros"] }
axum-macros = "0.3"
chrono = { version = "0.4.26", features = ["serde"] }
diesel = { version = "2.1", features = [
  "postgres",
  "extras",
  "postgres_backend",
] }
diesel_migrations = "2"
deadpool-diesel = { version = "0.4", features = ["postgres"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
tokio = { version = "1.0", features = ["sync", "macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.4", features = ["fast-rng", "v4", "serde"] }
bigdecimal = { version = "0.4.1", features = ["serde"] }
starknet = "0.6.0"
thiserror = "1.0.49"
utoipa = "4"
utoipa-swagger-ui = { version = "4", features = ["axum"] }
rdkafka = "0.36.0"
lazy_static = "1.4.0"
time = "0.3.29"

[dev-dependencies]
rstest = "0.18.2"
