timeout: 3600s

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: docker-build-ingestor
    args: [ 'build',
            '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pragma-ingestor:${TAG_NAME}',
            '--file=Dockerfile.ingestor',
            '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: docker-build-node
    args: [ 'build',
            '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pragma-node:${TAG_NAME}',
            '--file=Dockerfile.node',
            '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: docker-push-ingestor
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pragma-ingestor:${TAG_NAME}']
    waitFor: ['docker-build-ingestor']

  - name: 'gcr.io/cloud-builders/docker'
    id: docker-push-node
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pragma-node:${TAG_NAME}']
    waitFor: ['docker-build-node']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
