services:
  onchain-db:
    image: timescale/timescaledb-ha:pg17.4-ts2.18.2
    restart: always
    user: postgres
    networks:
      - pragma-db-network
    volumes:
      - ./sql/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./sql/02-create-publishers.sql:/docker-entrypoint-initdb.d/02-add-publishers.sql
      - ./sql/03-create-timescale-hypertables.sql:/docker-entrypoint-initdb.d/03-create-timescale-hypertables.sql
      - ./sql/04-create-timescale-median-aggregates.sql:/docker-entrypoint-initdb.d/04-create-timescale-median-aggregates.sql
      - ./sql/05-create-timescale-ohlc-aggregates.sql:/docker-entrypoint-initdb.d/05-create-timescale-ohlc-aggregates.sql
      - ./sql/06-create-timescale-twap-aggregates.sql:/docker-entrypoint-initdb.d/06-create-timescale-twap-aggregates.sql
      - ./sql/07-add-compression.sql:/docker-entrypoint-initdb.d/07-add-compression.sql
      - ./sql/08-create-indexes.sql:/docker-entrypoint-initdb.d/08-create-indexes.sql
      - onchain-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pragma
      - POSTGRES_PASSWORD=test-password
      - PGPORT=5433
    ports:
      - 5433:5433
    expose:
      - 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  offchain-db:
    image: timescale/timescaledb-ha:pg17.4-ts2.18.2
    restart: always
    user: postgres
    networks:
      - pragma-db-network
    volumes:
      - offchain-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pragma
      - POSTGRES_PASSWORD=test-password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pragma-zookeeper:
    container_name: "pragma-zookeeper"
    image: confluentinc/cp-zookeeper:latest
    restart: "always"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pragma-zookeeper-network
    volumes:
      - pragma_zookeeper_data:/var/lib/zookeeper/data
      - pragma_zookeeper_logs:/var/lib/zookeeper/log
    ports:
      - "22181:2181"

  pragma-kafka:
    container_name: "pragma-kafka"
    image: confluentinc/cp-kafka:latest
    depends_on:
      pragma-zookeeper:
        condition: service_started
    networks:
      - pragma-kafka-network
      - pragma-zookeeper-network
    ports:
      - "29092:29092"
      - "9092:9092"
    expose:
      - "29092"
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--list",
          "--bootstrap-server",
          "pragma-kafka:9092",
        ]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: pragma-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://pragma-kafka:9092,PLAINTEXT_E://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_E:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  pragma-ingestor-1:
    container_name: "pragma-ingestor-1"
    environment:
      - MODE=dev
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - DATABASE_MAX_CONN=25
      - BROKERS=pragma-kafka:9092
      - TOPIC=pragma-data
      - GROUP_ID=pragma-data
      - OFFCHAIN_DATABASE_URL=postgres://postgres:test-password@offchain-db:5432/pragma
      - ONCHAIN_DATABASE_URL=postgres://postgres:test-password@onchain-db:5433/pragma
    depends_on:
      pragma-kafka:
        condition: service_healthy
      offchain-db:
        condition: service_healthy
    networks:
      - pragma-kafka-network
      - pragma-db-network
    build:
      dockerfile: Dockerfile.ingestor

networks:
  pragma-db-network:
  pragma-kafka-network:
  pragma-zookeeper-network:

volumes:
  offchain-db-data:
  onchain-db-data:
  pragma_zookeeper_data:
  pragma_zookeeper_logs:
