path: "/"
container_port: 8080
alb_scheme: internal
health_check_path: "/node"
container_environment:
  - region: "eu-west-3"
  - prefix: "/conf/{{ SERVICE_NAME }}/{{ RUN_ENV }}"
  - keys:
      - DATABASE_URL
      - HOST
      - PORT