{{- $fullname := include "pragma-node.fullname" . }}
{{- if .Values.ingress }}
{{- range .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .name }}
  name: {{ .name }}
  {{- else if .suffix }}
  name: {{ $fullname }}-{{ .suffix }}-ingress
  {{- else }}
  name: {{ $fullname }}-ingress
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
