{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Consumers Lag",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingestor_consumer_lag_total_count",
     "legendFormat": "{{consumer_type}}"
    }
   ]
  },
  {
   "title": "Data staleness",
   "type": "stat",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingestor_data_staleness_seconds{service_name=\"pragma-ingestor-meter-service\"}",
     "legendFormat": "Staleness"
    }
   ]
  },
  {
   "title": "Error Rate of Db Operations",
   "type": "stat",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(ingestor_db_operations_count_total{status=\"Error\"}[5m])) /\n  sum(rate(ingestor_db_operations_count_total[5m]))\n) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}