path: "/"
container_port: 8080
health_check_path: "/node"
container_environment:
  - region: "eu-west-3"
  - prefix: "/conf/{{ SERVICE_NAME }}/{{ RUN_ENV }}"
  - keys:
      - TIMESCALE_DATABASE_URL
      - POSTGRES_DATABASE_URL
      - DATABASE_MAX_CONN
      - TOPIC
      - HOST
      - PORT
      - METRICS_PORT
      - KAFKA_BROKERS
