path: "/"
container_port: 8080
health_check_path: "/node"
container_environment:
  - region: "eu-west-3"
  - prefix: "/conf/{{ SERVICE_NAME }}/{{ RUN_ENV }}"
  - keys:
      - OFFCHAIN_DATABASE_URL
      - ONCHAIN_DATABASE_URL
      - DATABASE_MAX_CONN
      - TOPIC
      - HOST
      - PORT
      - KAFKA_BROKERS
