[package]
name = "pragma-consumer-examples"
version = "0.1.0"
edition = "2021"
authors = ["Pragma Labs <support@pragma.build>"]

[workspace]

[dependencies]
tokio = { version = "1.11.0", features = ["full"] }

pragma-consumer = { path = "../" }
