[package]
name = "pragma-entities"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", features = ["macros"] }
bigdecimal = { version = "0.4.1", features = ["serde"] }
chrono = { version = "0.4.26", features = ["serde"] }
deadpool-diesel = { version = "0.4", features = ["postgres"] }
diesel = { version = "2.1", features = [
  "postgres",
  "extras",
  "postgres_backend",
] }
diesel_migrations = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
starknet = "0.6.0"
thiserror = "1.0.49"
utoipa = "4"
uuid = { version = "1.4", features = ["fast-rng", "v4", "serde"] }
