[package]
name = "pragma-node"
version = "0.1.0"
edition = "2021"


[dependencies]
aws-config = { version = "1.5.1", features = ["behavior-version-latest"] }
aws-sdk-secretsmanager = "1.32.0"
axum = { version = "0.6", features = ["macros", "ws"] }
axum-macros = "0.3"
bigdecimal = { version = "0.4.1", features = ["serde"] }
chrono = { version = "0.4.26", features = ["serde"] }
deadpool-diesel = { version = "0.4", features = ["postgres"] }
diesel = { version = "2.1", features = [
  "postgres",
  "extras",
  "postgres_backend",
  "serde_json",
] }
diesel_migrations = "2"
dotenvy = "0.15"
envy = "0.4.2"
futures-util = "0.3.30"
lazy_static = "1.4.0"
pragma-common = { path = "../pragma-common", version = "1.0.0" }
pragma-entities = { path = "../pragma-entities", version = "1.0.0" }
pragma-monitoring = { git = "https://github.com/astraly-labs/pragma-monitoring", rev = "fab5233" }
rdkafka = "0.36.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
starknet = "0.9.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.49"
time = "0.3.29"
tokio = { version = "1.0", features = ["sync", "macros", "rt-multi-thread"] }
tower-http = { version = "0.4.0", features = ["fs", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.0"
utoipa = "4"
utoipa-swagger-ui = { version = "4", features = ["axum"] }
uuid = { version = "1.4", features = ["fast-rng", "v4", "serde"] }

[dev-dependencies]
rstest = "0.18.2"
