[profile.default]
# "retries" defines the number of times a test should be retried. If set to a
# non-zero value, tests that succeed on a subsequent attempt will be marked as
# flaky. Can be overridden through the `--retries` option.
# Examples
# * retries = 3
# * retries = { backoff = "fixed", count = 2, delay = "1s" }
# * retries = { backoff = "exponential", count = 10, delay = "1s", jitter = true, max-delay = "10s" }
retries = 0

# The number of threads to run tests with. Supported values are either an
# integer or the string "num-cpus". Can be overridden through the
# `--test-threads` option.
test-threads = "num-cpus"

# The number of threads required for each test. This is generally used in
# overrides to mark certain tests as heavier than others. However, it can also
# be set as a global parameter.
threads-required = 1

[[profile.default.overrides]]
filter = "package(tests)"
threads-required = "num-cpus"
run-extra-args = ["--test-threads=1"]

[profile.ci]
retries = 0
test-threads = "num-cpus" 

[[profile.ci.overrides]]
filter = "package(tests)"
run-extra-args = ["--test-threads=1"]
threads-required = "num-cpus"
