[package]
name = "pragma-common"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
starknet = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
thiserror = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
