name: Pragma CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout toml files
        uses: actions/checkout@v4
      - name: Run toml check
        run: npx @taplo/cli fmt --config ./taplo/taplo.toml --check

  Tests:
    name: Run tests Coverage
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout toml files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astraly-labs/workflows/rust/test@v1.0.6
        with:
          fail_ci: false

  Lint:
    permissions:
      security-events: write
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Rust Code Linting checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Rust Lint
        uses: astraly-labs/workflows/rust/lint@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  scanner:
    permissions:
      security-events: write
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Rust Code Scanning checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Rust Scanner
        uses: astraly-labs/workflows/rust/scan@v1.0.6
        with:
          codeql_upload: false
